### PR TITLE
Remove optional dependencies from install_requires

### PR DESCRIPTION
**Pull request by hpk**
Moved some dependencies that were only used for the examples and s2repoze plugin into `extras_require`:

- `paste`
- `zope.interface`
- `repoze.who`

Also removed `decorator`, which was unused.

This keeps those unused dependencies from being installed when doing a `pip install pysaml2`. This is especially important when using this library in other web frameworks, e.g. Django.

### CODE REVIEW

**Comment by hpk** [comment]
@rohe Any chance you could review this and offer a thumbs up/down? We're using pysaml2 with Django (thanks for your work, by the way!) but would love to use it in our pip requirements without pulling in all the unnecessary dependencies.

**Comment by rohe** [comment]
Let me have a look at it tomorrow. Won't have time tonight.

**Comment by liquidpele** [comment]
ping!  It would be nice not to have to pull in unnecessary libs...

**Comment by hpk** [comment]
Any update on this? Let me know if you have any questions about the setup.py changes. I understand this may require some changes to your own develop/test process, but it should be a cleaner install for all the downstream consumers of this library.

**Comment by liquidpele** [comment]
Well, the branch has conflicts now, so you'll want to merge in upstream to your branch and fix those.

**Pull request merged**
