### PR TITLE
example: set exact version of cherrypy.

### PR DESCRIPTION
**Pull request by schettino72**
Latest version of cherrypy does not work with current code.

### CODE REVIEW

**Comment by jkakavas** [comment]
I came across the issue same yesterday coincidently and I can verify that it works with cherrypy up to v8.9.1

**Comment by schettino72** [comment]
@jkakavas It did not work for me on version 8.9.1. 
I was getting a an error related to wsgiserver and bytes...
Which python version are you using? I was on python 2.7

**Comment by jkakavas** [comment]
You're right, I hadn't correlated these two. I solved that by monkey patching cherrypy at cherrypy/wsgiserver/__init__.py 

```python
try: 
   for chunk in filter(None, response):
       if not isinstance(chunk, six.binary_type):
           raise ValueError('WSGI Applications must yield bytes')
       self.write(chunk)
```

but #369 handles this correctly. 

So if this and #369 can be pulled together, we can go up to at least 8.9.1

**Comment by qianlei90** [comment]
Using cherrypy 7.1.0 solved the problem.

**Comment by c00kiemon5ter** [comment]
Latest patches should fix in the code.

**Pull request closed without merging**
