### PR TITLE
A plethora of python3 fixes

### PR DESCRIPTION
**Pull request by SpamapS**
The going is slower now, so I'm doing smaller bits of code. Trying hard to maintain a consistent interface, but this has required assuming everything moving through pysaml2 is utf-8, which may or may not be the case. Since XML allows specifying others, it may be a good idea to go back and add some tests specifically with non-UTF-8 encoded XML documents. Here are the latest results of test runs with python 3.4:

running test
/usr/lib/python3/dist-packages/setuptools/dist.py:266: UserWarning: Module argparse was already imported from /usr/lib/python3.4/argparse.py, but /home/clint/src/pysaml2/argparse-1.1-py3.4.egg is being added to sys.path
  working_set.add(dist, replace=True)
running egg_info
writing dependency_links to src/pysaml2.egg-info/dependency_links.txt
writing requirements to src/pysaml2.egg-info/requires.txt
writing top-level names to src/pysaml2.egg-info/top_level.txt
writing src/pysaml2.egg-info/PKG-INFO
reading manifest file 'src/pysaml2.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'README'
writing manifest file 'src/pysaml2.egg-info/SOURCES.txt'
running build_ext
================================================= test session starts ==================================================
platform linux -- Python 3.4.0 -- py-1.4.27 -- pytest-2.7.0
rootdir: /home/clint/src/pysaml2, inifile: 
collected 457 items / 8 errors 

tests/test_00_xmldsig.py ..............................................
tests/test_01_xmlenc.py ......
tests/test_02_saml.py ....F..FF................................F....................................
tests/test_03_saml2.py ....................F
tests/test_04_samlp.py ........................
tests/test_05_md.py ..........................................................
tests/test_10_time_util.py F.F..............
tests/test_12_s_utils.py ..................................
tests/test_13_validate.py .......
tests/test_19_attribute_converter.py .............
tests/test_20_assertion.py ................................
tests/test_22_mdie.py .
tests/test_30_mdstore.py ........
tests/test_30_mdstore_old.py ........
tests/test_31_config.py ............
tests/test_32_cache.py ..........
tests/test_33_identifier.py ......
tests/test_34_population.py ....
tests/test_36_mdbcache.py ......
tests/test_37_entity_categories.py ..FF..
tests/test_40_sigver.py ...............
tests/test_41_response.py ....
tests/test_42_enc.py ....
tests/test_43_soap.py ..
tests/test_44_authnresp.py ....
tests/test_62_vo.py EEEEEEEE
tests/test_66_name_id_mapping.py ..
tests/test_67_manage_name_id.py ..
tests/test_68_assertion_id.py .
tests/test_72_eptid.py ..
tests/test_75_mongodb.py ..
tests/test_76_metadata_in_mdb.py .
tests/test_77_authn_context.py ......
tests/test_81_certificates.py ....
tests/test_88_nsprefix.py ..
work/test.txt .

======================================================== ERRORS ========================================================
_______________________________________ ERROR collecting tests/test_50_server.py _______________________________________
tests/test_50_server.py:6: in <module>
    from urlparse import parse_qs
E   ImportError: No module named 'urlparse'
_______________________________________ ERROR collecting tests/test_51_client.py _______________________________________
tests/test_51_client.py:8: in <module>
    import urlparse
E   ImportError: No module named 'urlparse'
_________________________________________ ERROR collecting tests/test_60_sp.py _________________________________________
tests/test_60_sp.py:8: in <module>
    from saml2.s2repoze.plugins.sp import make_plugin
src/saml2/s2repoze/plugins/sp.py:16: in <module>
    from urlparse import parse_qs, urlparse
E   ImportError: No module named 'urlparse'
________________________________________ ERROR collecting tests/test_63_ecp.py _________________________________________
tests/test_63_ecp.py:10: in <module>
    from saml2 import ecp_client
src/saml2/ecp_client.py:10: in <module>
    import cookielib
E   ImportError: No module named 'cookielib'
______________________________________ ERROR collecting tests/test_64_artifact.py ______________________________________
tests/test_64_artifact.py:4: in <module>
    from urlparse import urlparse
E   ImportError: No module named 'urlparse'
____________________________________ ERROR collecting tests/test_65_authn_query.py _____________________________________
tests/test_65_authn_query.py:2: in <module>
    from urlparse import urlparse, parse_qs
E   ImportError: No module named 'urlparse'
_____________________________________ ERROR collecting tests/test_69_discovery.py ______________________________________
tests/test_69_discovery.py:2: in <module>
    from saml2.discovery import DiscoveryServer
src/saml2/discovery.py:1: in <module>
    from urllib import urlencode
E   ImportError: cannot import name 'urlencode'
__________________________________ ERROR collecting tests/test_70_redirect_signing.py __________________________________
tests/test_70_redirect_signing.py:10: in <module>
    from urlparse import parse_qs
E   ImportError: No module named 'urlparse'
______________________________________ ERROR at setup of TestVirtualOrg.test_mta _______________________________________

self = <class 'test_62_vo.TestVirtualOrg'>

    def setup_class(self):
        conf = config.SPConfig()
        conf.load_file("server_conf")
        self.sp = Saml2Client(conf)
    
>       vo_name = conf.vorg.keys()[0]
E       TypeError: 'dict_keys' object does not support indexing

tests/test_62_vo.py:36: TypeError
________________________________ ERROR at setup of TestVirtualOrg.test_unknown_subject _________________________________

self = <class 'test_62_vo.TestVirtualOrg'>

    def setup_class(self):
        conf = config.SPConfig()
        conf.load_file("server_conf")
        self.sp = Saml2Client(conf)
    
>       vo_name = conf.vorg.keys()[0]
E       TypeError: 'dict_keys' object does not support indexing

tests/test_62_vo.py:36: TypeError
_______________________________________ ERROR at setup of TestVirtualOrg.test_id _______________________________________

self = <class 'test_62_vo.TestVirtualOrg'>

    def setup_class(self):
        conf = config.SPConfig()
        conf.load_file("server_conf")
        self.sp = Saml2Client(conf)
    
>       vo_name = conf.vorg.keys()[0]
E       TypeError: 'dict_keys' object does not support indexing

tests/test_62_vo.py:36: TypeError
___________________________________ ERROR at setup of TestVirtualOrg.test_id_unknown ___________________________________

self = <class 'test_62_vo.TestVirtualOrg'>

    def setup_class(self):
        conf = config.SPConfig()
        conf.load_file("server_conf")
        self.sp = Saml2Client(conf)
    
>       vo_name = conf.vorg.keys()[0]
E       TypeError: 'dict_keys' object does not support indexing

tests/test_62_vo.py:36: TypeError
_____________________________________ ERROR at setup of TestVirtualOrg_2.test_mta ______________________________________

self = <class 'test_62_vo.TestVirtualOrg_2'>

    def setup_class(self):
        conf = config.SPConfig()
        conf.load_file("server_conf")
>       vo_name = conf.vorg.keys()[0]
E       TypeError: 'dict_keys' object does not support indexing

tests/test_62_vo.py:65: TypeError
_______________________________ ERROR at setup of TestVirtualOrg_2.test_unknown_subject ________________________________

self = <class 'test_62_vo.TestVirtualOrg_2'>

    def setup_class(self):
        conf = config.SPConfig()
        conf.load_file("server_conf")
>       vo_name = conf.vorg.keys()[0]
E       TypeError: 'dict_keys' object does not support indexing

tests/test_62_vo.py:65: TypeError
______________________________________ ERROR at setup of TestVirtualOrg_2.test_id ______________________________________

self = <class 'test_62_vo.TestVirtualOrg_2'>

    def setup_class(self):
        conf = config.SPConfig()
        conf.load_file("server_conf")
>       vo_name = conf.vorg.keys()[0]
E       TypeError: 'dict_keys' object does not support indexing

tests/test_62_vo.py:65: TypeError
__________________________________ ERROR at setup of TestVirtualOrg_2.test_id_unknown __________________________________

self = <class 'test_62_vo.TestVirtualOrg_2'>

    def setup_class(self):
        conf = config.SPConfig()
        conf.load_file("server_conf")
>       vo_name = conf.vorg.keys()[0]
E       TypeError: 'dict_keys' object does not support indexing

tests/test_62_vo.py:65: TypeError
======================================================= FAILURES =======================================================
_________________________________ TestExtensionContainer.test_add_extension_attribute __________________________________

self = <test_02_saml.TestExtensionContainer object at 0x7f8673bb6ac8>

    def test_add_extension_attribute(self):
        ec = saml2.ExtensionContainer()
        ec.add_extension_attribute("foo", "bar")
        assert len(ec.extension_attributes) == 1
>       assert ec.extension_attributes.keys()[0] == "foo"
E       TypeError: 'dict_keys' object does not support indexing

tests/test_02_saml.py:186: TypeError
________________________________________ TestSAMLBase.test_make_vals_multi_dict ________________________________________

self = <test_02_saml.TestSAMLBase object at 0x7f8673bbef28>

    def test_make_vals_multi_dict(self):
        ava = ["foo", "bar", "lions", "saints"]
    
        raises(Exception,
               "saml2.make_vals(ava, AttributeValue, Attribute(), part=True)")
    
        attr = Attribute()
        saml2.make_vals(ava, AttributeValue, attr, prop="attribute_value")
>       assert attr.keyswv() == ["name_format", "attribute_value"]
E       assert ['attribute_v...'name_format'] == ['name_format'...ribute_value']
E         At index 0 diff: 'attribute_value' != 'name_format'
E         Use -v to get the full diff

tests/test_02_saml.py:219: AssertionError
__________________________________________ TestSAMLBase.test_to_string_nspair __________________________________________

self = <test_02_saml.TestSAMLBase object at 0x7f8673cd31d0>

    def test_to_string_nspair(self):
        foo = saml2.make_vals("lions", AttributeValue, part=True)
        txt = foo.to_string()
        nsstr = foo.to_string({"saml": saml.NAMESPACE})
        assert nsstr != txt
        print(txt)
        print(nsstr)
>       assert "saml:AttributeValue" in nsstr
E       TypeError: Type str doesn't support the buffer API

tests/test_02_saml.py:229: TypeError
------------------------------------------------- Captured stdout call -------------------------------------------------
b'<ns0:AttributeValue xmlns:ns0="urn:oasis:names:tc:SAML:2.0:assertion" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">lions</ns0:AttributeValue>'
b'<saml:AttributeValue xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">lions</saml:AttributeValue>'
___________________________________________ TestAttribute.test_basic_base64 ____________________________________________

self = <test_02_saml.TestAttribute object at 0x7f8673cd3550>

    def test_basic_base64(self):
>       attribute = saml.attribute_from_string(BASIC_BASE64_AV)

tests/test_02_saml.py:689: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
src/saml2/saml.py:1160: in attribute_from_string
    return saml2.create_class_from_xml_string(Attribute, xml_string)
src/saml2/__init__.py:89: in create_class_from_xml_string
    return create_class_from_element_tree(target_class, tree)
src/saml2/__init__.py:119: in create_class_from_element_tree
    target.harvest_element_tree(tree)
src/saml2/__init__.py:307: in harvest_element_tree
    self._convert_element_tree_to_member(child)
src/saml2/__init__.py:477: in _convert_element_tree_to_member
    create_class_from_element_tree(member_class[0], child_tree))
src/saml2/__init__.py:119: in create_class_from_element_tree
    target.harvest_element_tree(tree)
src/saml2/saml.py:267: in harvest_element_tree
    _verify_value_type(typ, getattr(self, "text"))
src/saml2/saml.py:122: in _verify_value_type
    return base64.decodestring(val)
/usr/lib/python3.4/base64.py:561: in decodestring
    return decodebytes(s)
/usr/lib/python3.4/base64.py:553: in decodebytes
    _input_type_check(s)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

s = 'VU5JTkVUVA=='

    def _input_type_check(s):
        try:
            m = memoryview(s)
        except TypeError as err:
            msg = "expected bytes-like object, not %s" % s.__class__.__name__
>           raise TypeError(msg) from err
E           TypeError: expected bytes-like object, not str

/usr/lib/python3.4/base64.py:522: TypeError
________________________________________________ test_extensions_loadd _________________________________________________

    def test_extensions_loadd():
        ava = {"extension_elements": [
            {
                'attributes': {},
                'tag': 'ExternalEntityAttributeAuthority',
                'namespace': 'urn:oasis:names:tc:SAML:metadata:dynamicsaml',
                'children': [
                    {"tag": "AssertingEntity",
                     "namespace": "urn:oasis:names:tc:SAML:metadata:dynamicsaml",
                     "children": [
                         {"tag": "NameID",
                          "namespace": "urn:oasis:names:tc:SAML:metadata:dynamicsaml",
                          "text": "http://federationX.org",
                          "attributes": {
                              "Format": "urn:oasis:names:tc:SAML:2.0:nameid-format:entity"
                              },
                          }]
                    },
                    {
                        "tag": "RetrievalEndpoint",
                        "namespace": "urn:oasis:names:tc:SAML:metadata:dynamicsaml",
                        "text": "https://federationX.org/?ID=a87s76a5765da76576a57as",
                    }],
                }],
               "extension_attributes": {
                   "foo": "bar",
               }
        }
    
        extension = saml2.SamlBase()
        extension.loadd(ava)
    
        print(extension.__dict__)
        assert len(extension.extension_elements) == 1
        ee = extension.extension_elements[0]
        assert len(ee.children) == 2
        for child in ee.children:
            assert child.namespace == "urn:oasis:names:tc:SAML:metadata:dynamicsaml"
        assert _eq(["AssertingEntity", "RetrievalEndpoint"],
                   [c.tag for c in ee.children])
        aes = [c for c in ee.children if c.tag == "AssertingEntity"]
        assert len(aes) == 1
        assert len(aes[0].children) == 1
        assert _eq(aes[0].attributes.keys(), [])
        nid = aes[0].children[0]
        assert nid.tag == "NameID"
        assert nid.namespace == "urn:oasis:names:tc:SAML:metadata:dynamicsaml"
        assert len(nid.children) == 0
        assert _eq(nid.attributes.keys(), ["Format"])
        assert nid.text.strip() == "http://federationX.org"
    
>       assert extension.extension_attributes.keys() == ["foo"]
E       assert dict_keys(['foo']) == ['foo']
E         Use -v to get the full diff

tests/test_03_saml2.py:551: AssertionError
------------------------------------------------- Captured stdout call -------------------------------------------------
{'extension_attributes': {'foo': 'bar'}, 'text': None, 'extension_elements': [<saml2.ExtensionElement object at 0x7f8673d94f98>]}
___________________________________________________ test_f_quotient ____________________________________________________

    def test_f_quotient():
>       assert f_quotient(-1, 3) == -1
E       assert 0 == -1
E        +  where 0 = f_quotient(-1, 3)

tests/test_10_time_util.py:12: AssertionError
__________________________________________________ test_f_quotient_2 ___________________________________________________

    def test_f_quotient_2():
>       assert f_quotient(0, 1, 13) == -1
E       assert 0 == -1
E        +  where 0 = f_quotient(0, 1, 13)

    def test_filter_ava3():
        policy = Policy({
            "default": {
                "lifetime": {"minutes": 15},
                #"attribute_restrictions": None  # means all I have
                "entity_categories": ["swamid"]
            }
        })
    
        mds = MetadataStore(ONTS.values(), ATTRCONV, sec_config,
                            disable_ssl_certificate_validation=True)
        mds.imp([{"class": "saml2.mdstore.MetaDataFile", "metadata": [(full_path("entity_cat_sfs_hei.xml"), )]}])
    
        ava = {"givenName": ["Derek"], "sn": ["Jeter"],
               "mail": ["derek@nyy.mlb.com"], "c": ["USA"],
               "eduPersonTargetedID": "foo!bar!xyz",
               "norEduPersonNIN": "19800101134"}
    
        ava = policy.filter(ava, "urn:mace:example.com:saml:roland:sp", mds)
    
>       assert _eq(list(ava.keys()), ['eduPersonTargetedID', "norEduPersonNIN"])
E       assert _eq(['eduPersonTargetedID'], ['eduPersonTargetedID', 'norEduPersonNIN'])
E        +  where ['eduPersonTargetedID'] = list(dict_keys(['eduPersonTargetedID']))
E        +    where dict_keys(['eduPersonTargetedID']) = <built-in method keys of dict object at 0x7f8672773f08>()
E        +      where <built-in method keys of dict object at 0x7f8672773f08> = {'eduPersonTargetedID': 'foo!bar!xyz'}.keys

tests/test_37_entity_categories.py:103: AssertionError
___________________________________________________ test_filter_ava4 ___________________________________________________

    def test_filter_ava4():
        policy = Policy({
            "default": {
                "lifetime": {"minutes": 15},
                #"attribute_restrictions": None  # means all I have
                "entity_categories": ["swamid"]
            }
        })
    
        mds = MetadataStore(ONTS.values(), ATTRCONV, sec_config,
                            disable_ssl_certificate_validation=True)
        mds.imp([{"class": "saml2.mdstore.MetaDataFile", "metadata": [(full_path("entity_cat_re_nren.xml"), )]}])
    
        ava = {"givenName": ["Derek"], "sn": ["Jeter"],
               "mail": ["derek@nyy.mlb.com"], "c": ["USA"],
               "eduPersonTargetedID": "foo!bar!xyz",
               "norEduPersonNIN": "19800101134"}
    
        ava = policy.filter(ava, "urn:mace:example.com:saml:roland:sp", mds)
    
>       assert _eq(list(ava.keys()), ['eduPersonTargetedID', "givenName", "c", "mail",
                                "sn"])
E       assert _eq(['eduPersonTargetedID'], ['eduPersonTargetedID', 'givenName', 'c', 'mail', 'sn'])
E        +  where ['eduPersonTargetedID'] = list(dict_keys(['eduPersonTargetedID']))
E        +    where dict_keys(['eduPersonTargetedID']) = <built-in method keys of dict object at 0x7f8672b29d48>()
E        +      where <built-in method keys of dict object at 0x7f8672b29d48> = {'eduPersonTargetedID': 'foo!bar!xyz'}.keys

tests/test_37_entity_categories.py:126: AssertionError
=================================== 9 failed, 440 passed, 16 error in 27.40 seconds ====================================

### CODE REVIEW

**Comment by rohe** [comment]
> 26 maj 2015 kl. 23:45 skrev SpamapS <notifications@github.com>:
> 
> The going is slower now, so I'm doing smaller bits of code. Trying hard to maintain a consistent interface, but this has required assuming everything moving through pysaml2 is utf-8, which may or may not be the case. Since XML allows specifying others, it may be a good idea to go back and add some tests specifically with non-UTF-8 encoded XML documents.

I’ve always assumed utf-8 and have had no one complaining about that.
So, I guess it is a pretty good assumption.

But having a non-UTF-8 encoding test is a good idea.

- Roland

"It is the consequence of humanity. We are all formed of frailty and error; let us pardon reciprocally each others’ folly - that is the first law of nature.” - Voltaire

**Comment by SpamapS** [comment]
Ok, I have reached the point where I think my knowledge of pysaml2 and SAML in general is not sufficient to efficiently correct the last 5 tests that fail. I would very much appreciate some more experienced eyes. There are only 5 failures now, all that show some missing data. I suspect this is some filtering issue with strings vs. bytes. Please do address this quickly, so that CI can be enabled for python3. Every merge that has happened in the last 2 weeks since I've been working on this has added new python3 failures to be addressed.

**Comment by rohe** [comment]
> 28 maj 2015 kl. 20:08 skrev SpamapS <notifications@github.com>:
> 
> Ok, I have reached the point where I think my knowledge of pysaml2 and SAML in general is not sufficient to efficiently correct the last 5 tests that fail. I would very much appreciate some more experienced eyes. There are only 5 failures now, all that show some missing data. I suspect this is some filtering issue with strings vs. bytes. Please do address this quickly, so that CI can be enabled for python3. Every merge that has happened in the last 2 weeks since I've been working on this has added new python3 failures to be addressed.

OK, I’ll look at it tomorrow.

- Roland

"It is the consequence of humanity. We are all formed of frailty and error; let us pardon reciprocally each others’ folly - that is the first law of nature.” - Voltaire

**Comment by thomasgoirand** [comment]
Any update on this pull request? It's a very important one for me. It'd be also super cool to have the last remaining issues fixed.

**Pull request merged**
